version: '3'
services:
  db:
    image: postgres:latest
    ports:
        - "5433:5432"
    environment:
      POSTGRES_USER: pgws
      POSTGRES_PASSWORD: example
  ws:
    image: diogob/postgres-websockets
    environment:
      PGWS_DB_URI: postgres://pgws:example@db/pgws
      PGWS_JWT_SECRET: "auwhfdnskjhewfi34uwehdlaehsfkuaeiskjnfduierhfsiweskjcnzeiluwhskdewishdnpwe"
      PGWS_ROOT_PATH: /home/postgres-websockets/client-example
      PGWS_META_CHANNEL: 'server-info'
    ports:
        - "3000:3000"
    depends_on:
        - db
