name: Release

# Trigger the workflow on push or pull request, but only for the main branch
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: release / ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc: ["9.6.3"]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: roottoor
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres_ws_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}

    - uses: actions/cache@v2.1.3
      name: Cache ~/dist-newstyle
      with:
        path: ~/dist-newstyle
        key: ${{ matrix.os }}-${{ matrix.ghc }}-v3

    - name: Build
      run: |
        cabal build

    - name: Download ghr
      run: |
        curl -sSLO https://github.com/tcnksm/ghr/releases/download/v0.14.0/ghr_v0.14.0_linux_amd64.tar.gz
        curl -sSLO https://github.com/tcnksm/ghr/releases/download/v0.14.0/v0.14.0_SHASUMS
        sha256sum --check --ignore-missing v0.14.0_SHASUMS
        tar --strip-components=1 -zxvf ghr_v0.14.0_linux_amd64.tar.gz ghr_v0.14.0_linux_amd64/ghr

    - name: Calculate and save checksum
      run:  sha256sum `find dist-newstyle -executable -type f -name postgres-websockets` > dist-newstyle/postgres-websockets.sha256

    - name: Publish Release on GitHub
      run: |
        mkdir ./release
        cp dist-newstyle/postgres-websockets.sha256 `find dist-newstyle -executable -type f -name postgres-websockets` ./release/
        VERSION=$(awk '/^version: / { print $2 };' < postgres-websockets.cabal)
        ./ghr -t ${{ secrets.GITHUB_TOKEN }} ${VERSION} ./release
